### ISSUE TITLE
Why is it deprecated?

### ISSUE THREAD

**Issue by valenokk** [BretFisher/docker-vackup#11]
I'm sorry if this question is inappropriate, I'm new to development and GitHub in particular and just don't know where else to ask it.

The author states that this tool is obsolete, as new Docker Desktop extension provides same functionality. I mainly want to use this tool to export volumes from remote docker hosts, so Docker Desktop can't help me. 

Am I the only one missing anything here? I'm trying to find an easy-to-use and maintained solution, but but looks like it doesn't exist, I can't be the only person who needs it?

**Comment by BretFisher** [comment]
I don't believe I said this is deprecated, which is why it's still here. This repo is just a few Docker commands inside a tiny shell script, so if you wanted to use it, feel free. I don't expect anything to break because it's so simple and only runs basic Docker commands.

You could even skip this "tool" and just copy the shell commands from the `vacup` script to run on Docker directly. For example, do you want to copy the contents of a volume to a local .tar? It's [just one Docker command](https://github.com/BretFisher/docker-vackup/blob/5d3617102bfe7dd36ba735cb7012ee8b6542e3b7/vackup#L72-L76).

**Comment by adamasantares** [comment]
I don't think that new docker desktop tool can replace your script. Because it cannot be used for scripting such as backups bash scripts with scheduling by cron.

**Comment by BretFisher** [comment]
Sure, as mentioned, I never said it was deprecated.
